package com.rf.taskmodule.utils

/**
 * Created by rahul on 13/11/18
 */
enum class NextScreen {ENTER_PASSWORD,
    LOGIN, VERIFY_MOBILE, HOME, SIGNUP, CHANGE_MOBILE,MY_PROFILE,SELECT_ACCOUNT,FORGOT_PASSWORD,NEW_PASSWORD,SIGNIN,
    SELECT_SIGNUP_ACCOUNT, SERVICE_PREFERENCES, ADD_PLACE, DEVICE_CHANGE_SOFT_POPUP, DEVICE_CHANGE_HARD_POPUP
}
